### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GiggleLiu** [LWKJJONAK/Quantum_Neural_Network_Classifiers#2]
* [x] change Project.toml, name
* [x] clean up using
* [x] rename variables: https://docs.julialang.org/en/v1/manual/style-guide/
* [x] #6
